from aiohh.exceptions.base import AiohhError


class NetworkError(AiohhError):
    pass
